FROM node:16 AS builder

WORKDIR /opt/web
COPY package.json ./
RUN yarn install

ENV PATH="./node_modules/.bin:$PATH"

COPY . ./
RUN ng build

FROM nginx:1.17-alpine
COPY nginx.config /etc/nginx/conf.d/default.conf
COPY --from=builder /opt/web/dist/ecorp /usr/share/nginx/html
